config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  match '/404', :to => 'errors#not_found', :via => :all, as: :errors_not_found
  match '/500', :to => 'errors#internal_server_error', :via => :all, as: :errors_internal_server_error
  root 'static_pages#home'
  # get '/about' => 'static_pages#about'

  get '/logo', to: 'static_pages#logo'
  get '/cookie-policy', to: 'static_pages#cookie_policy'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/terms-of-use', to: 'static_pages#terms_of_use'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  get '/portions/new' => 'portions#new'
  get '/portions/:id' => 'portions#show', as: :portion
  post '/portions' => 'portions#create'
  post '/portions/new_recipe_portion', to: 'portions#create_from_post'

  get '/stock/new' => 'stocks#new_no_id', as: :stocks_new_no_id
  get '/stock/new/:cupboard_id/custom' => 'stocks#custom_new', as: :stocks_custom_new
  get '/stock/new/:cupboard_id' => 'stocks#new', as: :stocks_new
  get '/stock/picks' => 'stocks#picks'
  get '/stock/:id' => 'stocks#show', as: :stock
  get '/stock/:id/edit' => 'stocks#edit', as: :edit_stock
  get '/stock/delete/:id' => 'stocks#delete_stock', as: :delete_stock
  patch '/stock/:id' => 'stocks#update'
  post '/stock' => 'stocks#create'
  post '/stock/delete' => 'stocks#delete_stock_post'
  post '/stock/custom' => 'stocks#create_custom', as: :create_custom_stock
  post '/stock/toggle_portion' => 'stocks#toggle_shopping_list_portion'
  post '/stock/add_shopping_list' => 'stocks#add_shopping_list'
  post '/stock/new/:cupboard_id' => 'stocks#create', as: :create_stock
  post '/stock/new' => 'stocks#create_with_params', as: :create_stock_with_params
  get '/stock' => 'stocks#index'
  post '/stocks/new_cupboard_stock', to: 'stocks#create_from_post'
  post '/stocks/edit_cupboard_stock', to: 'stocks#update_from_post'

  get '/cupboards' => 'cupboards#index'
  get '/cupboards/demo' => 'cupboards#demo'
  get '/cupboards/new' => 'cupboards#new'
  get '/cupboards/share/:id' => 'cupboards#share', as: :cupboard_share
  get '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite'
  get '/cupboards/:id' => 'cupboards#show'
  post '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite', as: :accept_cupboard_invite
  get '/cupboards/:id/edit' => 'cupboards#edit', as: :edit_cupboard
  patch '/cupboards/:id/edit' => 'cupboards#update'
  post '/cupboards' => 'cupboards#create'
  post '/cupboards/name_update' => 'cupboards#location_update'
  put '/cupboards/:id/delete' => 'cupboards#delete'
  post '/cupboards/autosave_sorting' => 'cupboards#autosave_sorting'
  post '/cupboards/share/:id' => 'cupboards#share_request'
  post '/cupboards/delete_quick_add_stock' => 'cupboards#delete_quick_add_stock'
  post '/cupboards/delete_cupboard_stock' => 'cupboards#delete_cupboard_stock'
  post '/cupboards/delete_cupboard_user' => 'cupboards#delete_cupboard_user'
  post '/cupboards/planner_recipes' => 'cupboards#get_latest_planner_recipes'

  get '/ingredients' => 'ingredients#index'
  get '/ingredients/new' => 'ingredients#new'
  get '/ingredients/:id' => 'ingredients#show', as: :ingredient
  get '/ingredients/:id/edit' => 'ingredients#edit', as: :edit_ingredient
  patch '/ingredients/:id' => 'ingredients#update'
  post '/ingredients' => 'ingredients#create'
  post '/ingredients/default_size_update' => 'ingredient#default_size_update', as: :default_ingredient_size_update

  delete '/demo_logout',   to: 'sessions#demo_logout'

  get '/quick_add_stock/new', to: 'user_fav_stocks#new'
  get '/quick_add_stock/:id/edit', to: 'user_fav_stocks#edit', as: :quick_add_stock_edit

  get '/profile', to: 'users#profile', as: :user_profile
  post '/users/notifications', to: 'users#notifications'
  get '/users', to: 'users#index', as: :user_list

  devise_scope :user do get "/users/sign_out" => "devise/sessions#destroy" end

  # get '/google_login', to: redirect('/auth/google_oauth2')
  # get '/auth/google_oauth2/callback', to: 'users#google_auth'

  post '/feedback/submit' => 'feedback#submit'

  get '/planner', to: 'planner#index', as: :planner
  post '/planner', to: 'planner#refresh', as: :planner_refresh
  get '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  post '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  get '/list/:gen_id', to: 'planner#list', as: :shopping_list_share
  post '/planner/recipe_add', to: 'planner#recipe_add_to_planner'
  post '/planner/recipe_update', to: 'planner#recipe_update_in_planner'
  post '/planner/update_portion', to: 'planner#update_portion'
  post '/planner/recipe_delete', to: 'planner#delete_recipe_from_planner'

  resources :user_fav_stocks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/recipes/portion_delete', to: 'recipes#portion_delete'
  post '/recipes/add_image', to: 'recipes#add_image'
  get '/recipes/favourites', to: 'recipes#favourites', as: :favourite_recipes
  get '/recipes/yours', to: 'recipes#yours', as: :your_recipes
  post '/recipes/update_matches', to: 'recipes#update_recipe_matches'

  resources :recipes do
    member do
      # get 'add_to_shopping_list'
      get 'favourite'
      get 'publish_update', as: 'publish_update'
      get 'delete', as: 'delete'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
	def logo
		render action: "logo", layout: "plain"
	end
	def cookie_policy
	end
	def privacy_policy
	end
	def terms_of_use
	end
	def about
	end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>

<h1>About Us</h1>

<h2>Who are we?</h2>

<p>The team behind getstockcubes.com is <a href="https://twitter.com/josh_harrington">Josh Harrington</a> and <a href="https://www.chantymarie.com">Chantelle Bradley</a>.</p>

<p>We're based in Essex in the UK.</p>

<h2>Why did we build getstockcubes.com?</h2>

<p>We wanted a tool that could help us manage the food in our cupboards and help us reduce our food waste. We had a look round and couldn't find anything that matched that concept so we started building it.</p>

<h2>How much does it cost?</h2>

<p>Right now we've chosen to put out the service for free to see if other people find it useful. Eventually we imagine that we would ask for a small monthly subscription to keep our systems running.</p>

<h2>How do I get started?</h2>

<p>If you haven't already got an account, you can <a href="/signup">sign up</a>.</p>

<ol>
	<li><p>Once you're setup, you can head over to <a href="/recipes">Recipes</a> and start searching round for recipes you like the look of</p></li>
	<li><p>You can add recipes to your favourites or to your shopping list</p></li>
	<li><p>If you have some recipes in your shopping list you can see what ingredients you'd need for those recipes</p></li>
	<li><p>[NOT BUILT] You can then use this list as you're wandering round the shops if you want</p></li>
	<li><p>[NOT BUILT] You can choose to then move all those ingredients that you've just bought over into your cupboards</p></li>
	<li><p>Now you'll see those ingredients in your cupboards (you can always add or edit these cupboards)</p></li>
	<li><p>You'll get information about their use by dates which we've estimated and you can update if you like</p></li>
</ol>

app/views/static_pages/cookie_policy.html.erb
<% provide(:title, 'Cookies Policy') %>

<style>
	.content {
    max-width: 90rem;
    padding-left: 2rem;
		padding-right: 2rem;
		margin: 4rem auto 0;
	}

	.content p,
	.content li {
		line-height: 1.6
	}

	.content ol,
	.content ul {
		padding-left: 2rem;
		font-size: 1.5rem;
	}

	.content *:not(h1):not(h2) {
		font-size: 1.5rem
	}

	.content ol {
		list-style: decimal;
	}
	.content ol li {
		font-size: 1.8rem;
		margin-top: 1.2rem;
	}

	.content ul {
		list-style: disc;
		margin-bottom: .8rem;
	}

	.content h1 {
		font-size: 3rem;
		margin-bottom: 1.4rem;
	}

	.content h2 {
		margin-bottom: .8rem;
	}

	.content table {
		margin-top: .8rem;
		overflow-x: auto;
    max-width: 100%;
	}

	.content table td {
		border: 1px solid #9e9e9e;
    padding: .4rem 0.6rem;
	}

</style>

<section class="content">

	<h1>Cookies policy</h1>

	<p>We use cookies on our website. You’ll find a notice about this on our homepage as well, which also links back to this policy.</p>
	<p>If you use this website after we’ve displayed the notice to you, we will treat this as your consent to our use of cookies for the purposes that we’ve explained below in our policy.</p>
	<p>We last updated our policy on April 3, 2020.</p>

	<ol>
		<li>
			<h2>Information about cookies</h2>
			<p>A cookie is a small text file that is placed onto your computer (or other electronic device) when you access our website.</p>
			<p>There are 4 different types of cookies:</p>
			<ul>
				<li>
					<p>Strictly-necessary cookies (required for the website to run). These allow you to do things like log in securely.</p>
				</li>
				<li>
					<p>Performance cookies (which measure how many visitors use our site, which pages they visit and how they interact with the site). These help us to improve our website.</p>
				</li>
				<li>
					<p>Functionality cookies (which remember specific visitor’s preferences for the way they use our site, e.g. language settings or font size).</p>
				</li>
				<li>
					<p>Targeting/advertising cookies (these collect information about individual visitors that enable us, or third parties, to provide relevant advertisements to those who have visited our site)</p>
				</li>
			</ul>
			<p>Our website may use each type of cookie in order to:</p>
			<ul>
				<li>
					<p>Make your online experience more efficient and enjoyable</p>
				</li>
				<li>
					<p>Improve our services</p>
				</li>
				<li>
					<p>Recognise you whenever you visit this website and distinguish you from other users of our site</p>
				</li>
				<li>
					<p>Obtain information about your preferences and use of our site</p>
				</li>
				<li>
					<p>Provide you with advertising that is tailored to your interests</p>
				</li>
				<li>
					<p>Carry out research and data analysis to help us to improve our content and services and to better understand our customer preferences and interests</p>
				</li>
			</ul>
			<p>Your web browser places cookies on your hard drive for record-keeping purposes and sometimes to track information about you.</p>
			<p>We have set out specific details of the cookies we use on our site in section 4 below.</p>
		</li>
		<li><h2>Third-party cookies</h2>
			<p>Like many other websites, third parties may also set cookies on our website. These third parties are responsible for the cookies they set on our site and we have no control over them. For further information on how their cookies policies work, please visit their websites.</p></li>
		<li><h2>Managing cookies</h2>
			<p>You can manage cookies yourself.</p>
			<p>You can set your web browser to refuse cookies, delete cookies, or to alert you when cookies are being sent.</p>
			<p>You will need to visit the web browser’s site to manage, but for ease we have provided links to popular browsers below:</p>
			<ul>
				<li>
					<p>Google Chrome: <a href="https://support.google.com/accounts/answer/61416?co=GENIE.Platform%3DDesktop&amp;hl=en">https://support.google.com/accounts/answer/61416?co=GENIE.Platform%3DDesktop&amp;hl=en</a>
					</p>
				</li>
				<li>
					<p>Microsoft Firefox: <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences">https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</a></p>
				</li>
				<li>
					<p>Microsoft Internet Explorer: <a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies">https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</a></p>
				</li>
				<li>
					<p>Apple Safari: <a href="https://support.apple.com/kb/ph21411?locale=en_US">https://support.apple.com/kb/ph21411?locale=en_US</a></p>
				</li>
			</ul>
			<p>For further information about cookies and how to manage or disable them please go to:
					<a href="https://www.aboutcookies.org/">www.aboutcookies.org</a>.</p>
			<p>Please also note that if you change/block cookies then:</p>
			<ul>
				<li>
					<p>some parts of our website may not function properly or as well as they otherwise might;</p>
				</li>
				<li>
					<p>changes will apply across all websites that you visit (unless you choose to block cookies only from particular websites); and</p>
				</li>
				<li>
					<p>the settlings that you change will only apply on the device on which you change the settings and will not apply across all other devices that you use.</p>
				</li>
			</ul></li>
		<li><h2>Specific details</h2>
			<p>We have set out in the table below details of each of the cookies on our site, a description of what they do and, where relevant, external links that provide more information about them:</p>
			<table>
				<tr>
					<td>
						<p><strong>Cookie Name</strong></p>
					</td>
					<td>
						<p><strong>Description</strong></p>
					</td>
					<td>
						<p><strong>External Information (if relevant)</strong></p>
					</td>
				</tr>
				<tr>
					<td>
						<p><strong>Google Analytics</strong></p>
					</td>
					<td>
						<p>We use Google Analytics to analyse the use of this website. Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users&apos; computers. The information generated relating to our website is used to create reports about the use of the website. Google will store this information.</p>
					</td>
					<td style="word-break:break-word;">
						<p>Google's privacy policy is available at: <a href="http://www.google.com/privacypolicy.html">http://www.google.com/privacypolicy.html</a></p>
					</td>
				</tr>
				<tr>
					<td>
						<p><strong>Hotjar</strong></p>
					</td>
					<td>
						<p>We use Hotjar to further analyse the use of this website. Hotjar provides visualisations of user behaviour to allow us to improve the usability of the website.</p>
					</td>
					<td style="word-break:break-word;">
						<p>Hotjar's privacy policy is available at: <a href="https://www.hotjar.com/legal/policies/privacy/">https://www.hotjar.com/legal/policies/privacy/</a></p>
					</td>
				</tr>
			</table></li>
	</ol>
</section>

app/views/static_pages/elements.html.erb
<% provide(:title, 'Elements page') %>

<h1>Elements Page</h1>

<form action="#na">

	<input type="text" placeholder="Text placeholder">
	<input type="number" placeholder="Number placeholder">

</form>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<style>
  html {
    scroll-behavior: smooth;
  }
  .banner_bar {
    background-color: #ddf4f2;
    padding-top: 6rem;
    padding-bottom: 6rem;
  }
  .banner_bar-text {
    margin-bottom: 3rem;
  }
  .banner_bar h1 {
    font-size: 4rem;
  }
  .banner_bar h2 {
    font-size: 2.3rem;
  }
  .bottom_banner_bar {
    background-color: #ddf4f2;
    padding-top: 6rem;
    padding-bottom: 6rem;
    text-align: center;
  }
  .bottom_banner_bar p {
    font-size: 2.6rem;
  }
  .bottom_banner_bar p + p {
    margin-top: 1rem;
  }
  .call_out_bar {
    background-color: #a2d7d2;
    padding-top: 8rem;
    padding-bottom: 8rem;
  }
  .call_out_bar h3 {
    font-size: 2.6rem;
    text-align: center;
  }
  @media all and (max-width:40rem) {
    .call_out_bar br {
      display:none;
    }
  }

  .q-a-block {
    margin-bottom: 9rem;
  }
  .question {
    font-size: 1.5rem;
    margin-top: 8rem;
  }
  .answer {
    font-size: 1.3rem;
    margin-top: .5rem;
  }
  .answer p {
    line-height: 1.4;
  }

  .perspective {
    perspective: 1500px;
    height: 14rem;
    width: 28rem;
    font-size: 1.2rem;
    margin-left: 2rem;
    margin-right: -2rem;
    margin-top: -5rem;
    margin-bottom: 7rem;
  }

  .cube {
    font-size: 4em;
    width: 2em;
    margin: 1.5em auto;
    transform-style: preserve-3d;
    transform: rotateX(-8deg) rotateY(40deg);}
    .cube:hover .banana,
    .cube:focus .banana {
      transform: rotate(-15deg);
    }
    .cube:hover .front,
    .cube:focus .front {
      transform: translateZ(1em) translateX(1.2em);
    }

  .side {
    position: absolute;
    width: 2em;
    height: 2em;
    color: white;
    text-align: center;
    line-height: 2em;
  }

  .front  {
    transform: translateZ(1em) translateX(.4em);
    transition: transform .3s;
    background-color: #AAE2DE;
  }
  .top {
    transform: rotateX( 90deg)  translateZ(1em);
    background-color: #C3EBE9;
  }
  .right {
    transform: rotateY( 90deg) translateZ(1em);
    background-color: #4CB0A8;
  }
  .left {
    transform: rotateY(-90deg) translateZ(1em);
    background-color: #98DCD8;
  }
  .bottom {
    transform: rotateX(-90deg) translateZ(1em);
    background-color: #60BDB7;}
    .bottom:before {
      content: "";
      width: .5em;
      height: .4em;
      transform: translateY(.75em) translateX(.3em);
      background-color: rgba(0,0,0,0.15);
      position: absolute;
      border-radius: 50%;
      animation: .8s infinite shrink-shadow;
    }
  .shadow {
    transform: rotateX(-90deg) translateZ(1em) translateX(-2em);
    background-color: #42948E;
  }
  .back {
    transform: rotateY(-180deg) translateZ(1em);
    background-color: #41A39B;
  }

  .banana {
    position: absolute;
    transition: transform .2s .2s;
    transform: rotate(-20deg);
    width: .9em;
    height: 1.3em;
    margin-left: 1.5em;
    margin-top: .6em;
    background-color:transparent;
    border-radius: 50%;
    box-shadow: -.2em 1px 0 -.05em rgba(0,0,0,0.1), -.4em 0 0 #ffd700;
    animation: 1.2s infinite wiggle;}
    .banana:before {
      content: "";
      position: absolute;
      width: .1em;
      height: .2em;
      left: .2em;
      top: -.1em;
      background-color: #daa520;
      border-radius: .01em .01em .2em .1em;
      transform: rotate(66deg);
    }

  @keyframes wiggle {
    0% {
      margin-top:.6em;
    }
    50% {
      margin-top: .5em;
    }
    100% {
      margin-top:.6em;
    }
  }
  @keyframes shrink-shadow {
    0% {
      width: .5em;
      height: .4em;
    }
    50% {
      width: .4em;
      height: .3em;
    }
    100% {
      width: .5em;
      height: .4em;
    }
  }
  .tour_jumper {
    background-color: var(--teal-40);
    padding: 1.7rem 0 3.8rem;
    display: block;
    font-size: 1.2rem;
    text-decoration: none;
    color: black;
    cursor: pointer;
  }
  .tour_jumper:hover {
    background-color: var(--teal-70);
  }

  .tour_jumper:hover .icon-arrow_forward {
    animation: 1s ease-in infinite bounce;
  }

  @keyframes bounce {
    0% {
      top:3rem;
    }
    50% {
      top: 3.5rem;
    }
    100% {
      top: 3rem;
    }
  }

  .tour_jumper * {
    pointer-events: none;
  }

  .tour_jumper--contents {
    display: flex;
    flex-direction: column;
    align-items: center;
    position: relative;
  }
  .tour_jumper--contents p {
    margin-bottom: .6rem;
  }

  .tour_jumper--contents .icon-arrow_forward {
    transform: rotate(90deg);
    width: 2rem;
    height: 2rem;
    position: absolute;
    top: 3rem;
  }

  #tour_video {
    padding: 3rem 0 5rem;
  }

  #tour_video > div {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  #tour_video h3 {
    font-size: 2.3rem;
    margin-bottom: 2rem;
  }

  #tour_video iframe {
    max-width: 90%;
    max-height: 55vw;
    width: 74rem;
    height: 45rem;
  }

  #tour_video a {
    background-color: var(--teal-110);
    display: block;
    padding: 0.9rem 1.7rem;
    margin-top: 4rem;
    color: white;
    text-decoration: none;
    font-size: 2rem;
    border-radius: 3px;
  }

  #tour_video a:hover,
  #tour_video a:focus {
    background-color: var(--teal-100);
  }

</style>

<section class="banner_bar">
  <div class="standard-wrapper flex items-center flex-wrap justify-around">
    <div class="banner_bar-text">
      <h1>Stockcubes</h1>
      <h2>Fighting food waste at home</h2>
    </div>

    <!-- Attributions:

    Banana from Lynn Fisher's brilliant https://a.singlediv.com/

    Perspective cube by Hugo Giraudel. As featured on css-tricks.com
    https://css-tricks.com/almanac/properties/p/perspective/
    -->
    <div class="perspective">
      <div class="cube">
        <div class="side front"></div>
        <div class="side back"></div>
        <div class="side right"></div>
        <div class="side left"></div>
        <div class="side top"></div>
        <div class="side bottom"></div>
        <div class="side shadow"></div>
        <div class="banana"></div>
      </div>
    </div>
  </div>
</section>

<section class="call_out_bar">
  <div class="standard-wrapper">
    <h3>We're here to make it ridiculously simple to <br /><strong>plan your meals</strong> and <strong>cut your food waste</strong></h3>
  </div>
</section>

<section class="tour_jumper">
  <div class="standard-wrapper tour_jumper--contents">
    <p>Check out the tour</p>
    <%= icomoon('arrow_forward') %>
  </div>
</section>


<section class="standard-wrapper q-a-block">

  <div class="question">
    <p><strong>Why should you care about food waste?</strong></p>
  </div>

  <div class="answer">
    <p>Well, it’s a big deal. No, really it’s massive, if you plot the emissions of food waste as it degrades, against the emissions of all the countries in the world - the only countries that produce more greenhouse gases are the US and China.</p>
  </div>

  <div class="question">
    <p><strong>But, maybe this isn’t really our problem?</strong></p>
  </div>

  <div class="answer">
    <p>In the UK, 6.6 Millions tonnes of food are wasted annually. We waste 70% of that total in our homes!</p>
  </div>

  <div class="question">
    <p><strong>Ok, but we’re really busy actually living our lives</strong></p>
  </div>

  <div class="answer">
    <p>Stockcubes wants to empower people to stop wasting food, plus there’s another benefit we haven’t mentioned yet. The dosh. The cashola. The money that you save by using your food more efficiently. In the UK, the average family would save up to £800 in a year by cutting their food waste.</p>
  </div>

  <div class="question">
    <p><strong>Right, fine, but surely it’s really difficult to solve?</strong></p>
  </div>

  <div class="answer">
    <p>It can be difficult, if you’re keeping track of all your food on paper and planning your meals by scouring cookbooks, but that’s where Stockcubes comes in. We’ve got delicious, simple recipes, a planner that builds you a shopping list and a recommendation engine that nudges you to use up the food you’ve already got.</p>
  </div>

</section>

<section class="bottom_banner_bar">
  <p><strong>Where do you sign up?</strong><p>
  <p>Right here: <%= link_to "Sign up", new_user_registration_path %>
</section>

<section id="tour_video">
  <div class="standard-wrapper">
    <h3>Take a tour of the Stockcubes platform</h3>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/puqc09GIO0I" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <%= link_to "Sign up", new_user_registration_path %>
  </div>
</section>

app/views/static_pages/logo.html.erb
<img src="<%= asset_pack_path('assets/images/social_profile.jpg') %>" alt="Stockcubes logo">

app/views/static_pages/old_home.html.erb
<% provide(:title, 'Home') %>
  <section class="feature-banner--title">
    <div class="feature-banner--title-content">
      <h1>Stockcubes</h1>
      <p class="def-breakdown">/stɒk|kjuːb/</p>
      <p class="def-typ">noun</p>
      <ol>
        <li><p>a system to help you keep aware of the food you've got</p></li>
        <li><p>something to help you make efficient meal decisions and reduce your food waste</p></li>
      </ol>
    </div>
  </section>
  <article class="feature-banner--collection">
    <section class="feature-banner">
      <% if user_signed_in? %>
        <p class="feature_text--minor">Stockcubes is a platform to help you keep track of what you have in your cupboards. We're just getting started, if you're keen to find out what's going on behind the scenes you can <a href="mailto:beta@getstockcubes.com?subject=Beta%20Club" target="_blank">email us</a> to become part of our Beta Love Club - you'll find out about new features first and be able to give feedback to help guide the direction of the service :)</p>
      <% else %>
        <p class="feature_text--minor">Stockcubes is a platform to help you keep track of what you have in your cupboards. We're just getting started, if you're keen to see what we're working on you can sign up or <a href="mailto:beta@getstockcubes.com?subject=Beta%20Club" target="_blank">email us</a> to become part of our Beta Love Club to find out about new features first and give feedback to help guide the direction of the service :)</p>
        <%= link_to "Sign up for free today!", new_user_registration_path, class: "pretty_form--submit_button" %>
      <% end %>
    </section>
  </article>
  <hr>
  <article class="feature-banner--collection">
    <section class="feature-banner">
      <div class="feature-banner--img">
        <%= large_svg('stock_in_cube', '0 0 950 504') %>
      </div>
      <div class="feature-banner--content">
        <p>See what's in your cupboards</p>
        <p>wherever you are</p>
      </div>
    </section>

    <section class="feature-banner">
      <div class="feature-banner--img">
        <%= large_svg('stock_addition', '0 0 502 112') %>
      </div>
      <div class="feature-banner--content">
        <p>Get recipe suggestions</p>
        <p>based on your ingredients</p>
      </div>
    </section>

    <section class="feature-banner">
      <div class="feature-banner--img">
        <%= large_svg('recipes_to_list', '0 0 1315 437') %>
      </div>
      <div class="feature-banner--content">
        <p>Build shopping lists</p>
        <p>with your favourite recipes</p>
      </div>
    </section>
  </article>

  <hr>
  <article class="feature-banner--sibling">
    <section>
    <% if current_user && current_user.demo == true %>
      <p>Sound good?</p>
      <p>
      <% if current_user && current_user.demo == true %>
        <% if request.host == 'demo.getstockcubes.com' %>
          <%= link_to 'Sign up today', 'https://www.getstockcubes.com/signup' %> on the main site
        <% else %>
          <%= link_to 'Sign up today', demo_logout_path, method: :delete %>
        <% end %>
      <% end %>
      </p>
    <% end %>
    <% unless user_signed_in? %>
      <p>
        Not yet convinced? Check out the <%= link_to 'demo site', 'https://demo.getstockcubes.com' %>
      </p>
    <% end %>
    <% if current_user && current_user.demo == false && request.host != 'demo.getstockcubes.com' %>
    <p>
      Unsure about how things work, check out the <%= link_to 'demo site', 'https://demo.getstockcubes.com' %>
    </p>
    <p>Alternatively you can contact us by <%= link_to 'email', 'mailto:help@getstockcubes.com', target: '_blank' %> or on twitter
    <%= link_to '@stock_cubes',  'https://twitter.com/stock_cubes' %>
    </p>
    <% end %>
    </section>
  </article>