config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  match '/404', :to => 'errors#not_found', :via => :all, as: :errors_not_found
  match '/500', :to => 'errors#internal_server_error', :via => :all, as: :errors_internal_server_error
  root 'static_pages#home'
  # get '/about' => 'static_pages#about'

  get '/logo', to: 'static_pages#logo'
  get '/cookie-policy', to: 'static_pages#cookie_policy'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/terms-of-use', to: 'static_pages#terms_of_use'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  get '/portions/new' => 'portions#new'
  get '/portions/:id' => 'portions#show', as: :portion
  post '/portions' => 'portions#create'
  post '/portions/new_recipe_portion', to: 'portions#create_from_post'

  get '/stock/new' => 'stocks#new_no_id', as: :stocks_new_no_id
  get '/stock/new/:cupboard_id/custom' => 'stocks#custom_new', as: :stocks_custom_new
  get '/stock/new/:cupboard_id' => 'stocks#new', as: :stocks_new
  get '/stock/picks' => 'stocks#picks'
  get '/stock/:id' => 'stocks#show', as: :stock
  get '/stock/:id/edit' => 'stocks#edit', as: :edit_stock
  get '/stock/delete/:id' => 'stocks#delete_stock', as: :delete_stock
  patch '/stock/:id' => 'stocks#update'
  post '/stock' => 'stocks#create'
  post '/stock/delete' => 'stocks#delete_stock_post'
  post '/stock/custom' => 'stocks#create_custom', as: :create_custom_stock
  post '/stock/toggle_portion' => 'stocks#toggle_shopping_list_portion'
  post '/stock/add_shopping_list' => 'stocks#add_shopping_list'
  post '/stock/new/:cupboard_id' => 'stocks#create', as: :create_stock
  post '/stock/new' => 'stocks#create_with_params', as: :create_stock_with_params
  get '/stock' => 'stocks#index'
  post '/stocks/new_cupboard_stock', to: 'stocks#create_from_post'
  post '/stocks/edit_cupboard_stock', to: 'stocks#update_from_post'

  get '/cupboards' => 'cupboards#index'
  get '/cupboards/demo' => 'cupboards#demo'
  get '/cupboards/new' => 'cupboards#new'
  get '/cupboards/share/:id' => 'cupboards#share', as: :cupboard_share
  get '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite'
  get '/cupboards/:id' => 'cupboards#show'
  post '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite', as: :accept_cupboard_invite
  get '/cupboards/:id/edit' => 'cupboards#edit', as: :edit_cupboard
  patch '/cupboards/:id/edit' => 'cupboards#update'
  post '/cupboards' => 'cupboards#create'
  post '/cupboards/name_update' => 'cupboards#location_update'
  put '/cupboards/:id/delete' => 'cupboards#delete'
  post '/cupboards/autosave_sorting' => 'cupboards#autosave_sorting'
  post '/cupboards/share/:id' => 'cupboards#share_request'
  post '/cupboards/delete_quick_add_stock' => 'cupboards#delete_quick_add_stock'
  post '/cupboards/delete_cupboard_stock' => 'cupboards#delete_cupboard_stock'
  post '/cupboards/delete_cupboard_user' => 'cupboards#delete_cupboard_user'
  post '/cupboards/planner_recipes' => 'cupboards#get_latest_planner_recipes'

  get '/ingredients' => 'ingredients#index'
  get '/ingredients/new' => 'ingredients#new'
  get '/ingredients/:id' => 'ingredients#show', as: :ingredient
  get '/ingredients/:id/edit' => 'ingredients#edit', as: :edit_ingredient
  patch '/ingredients/:id' => 'ingredients#update'
  post '/ingredients' => 'ingredients#create'
  post '/ingredients/default_size_update' => 'ingredient#default_size_update', as: :default_ingredient_size_update

  delete '/demo_logout',   to: 'sessions#demo_logout'

  get '/quick_add_stock/new', to: 'user_fav_stocks#new'
  get '/quick_add_stock/:id/edit', to: 'user_fav_stocks#edit', as: :quick_add_stock_edit

  get '/profile', to: 'users#profile', as: :user_profile
  post '/users/notifications', to: 'users#notifications'
  get '/users', to: 'users#index', as: :user_list

  devise_scope :user do get "/users/sign_out" => "devise/sessions#destroy" end

  # get '/google_login', to: redirect('/auth/google_oauth2')
  # get '/auth/google_oauth2/callback', to: 'users#google_auth'

  post '/feedback/submit' => 'feedback#submit'

  get '/planner', to: 'planner#index', as: :planner
  post '/planner', to: 'planner#refresh', as: :planner_refresh
  get '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  post '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  get '/list/:gen_id', to: 'planner#list', as: :shopping_list_share
  post '/planner/recipe_add', to: 'planner#recipe_add_to_planner'
  post '/planner/recipe_update', to: 'planner#recipe_update_in_planner'
  post '/planner/update_portion', to: 'planner#update_portion'
  post '/planner/recipe_delete', to: 'planner#delete_recipe_from_planner'

  resources :user_fav_stocks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/recipes/portion_delete', to: 'recipes#portion_delete'
  post '/recipes/add_image', to: 'recipes#add_image'
  get '/recipes/favourites', to: 'recipes#favourites', as: :favourite_recipes
  get '/recipes/yours', to: 'recipes#yours', as: :your_recipes
  post '/recipes/update_matches', to: 'recipes#update_recipe_matches'

  resources :recipes do
    member do
      # get 'add_to_shopping_list'
      get 'favourite'
      get 'publish_update', as: 'publish_update'
      get 'delete', as: 'delete'
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :portions, dependent: :delete_all
  has_many :ingredients, through: :portions
  has_many :planner_recipes, dependent: :delete_all
  has_many :steps, class_name: "RecipeStep", dependent: :delete_all
  accepts_nested_attributes_for :steps
  has_many :recipe_authors, dependent: :delete_all
  has_many :authors, through: :recipe_authors

  belongs_to :user, optional: true

  # Favourited by users
  has_many :favourite_recipes # just the 'relationships'
  has_many :users, through: :favourite_recipes # the actual users favouriting a recipe

  has_many :user_recipe_stock_matches

  accepts_nested_attributes_for :portions,
  :reject_if => :all_blank,
  :allow_destroy => true
  accepts_nested_attributes_for :ingredients

  validates_presence_of :title

  def slug
    title.downcase.gsub(/[\ \,\/]/, ',' => '', ' ' => '_', '/' => '_')
  end

  def to_param
    "#{id}-#{slug}"
  end

  searchkick

  scope :search_import, -> { where(live: true, public: true) }

  def search_data
    {
      title: title,
      cuisine: cuisine,
      description: description,
      ingredient_names: ingredients.map(&:name)
    }
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper

	def vegan?(recipe)
		if recipe.ingredients.none?{ |ingredient| ingredient.vegan == false }
			return true
		end
	end
	def vegetarian?(recipe)
		if recipe.ingredients.none?{ |ingredient| ingredient.vegetarian == false }
			return true
		end
	end
	def gluten_free?(recipe)
		if recipe.ingredients.none?{ |ingredient| ingredient.gluten_free == false }
			return true
		end
	end
	def dairy_free?(recipe)
		if recipe.ingredients.none?{ |ingredient| ingredient.dairy_free == false }
			return true
		end
	end
	def kosher?(recipe)
		if recipe.ingredients.none?{ |ingredient| ingredient.kosher == false }
			return true
		end
	end
	def portion_amount_unit_and_ingredient(portion)

		## check if ingredient unit is correct unit, fallback to portion unit if different
		if portion.unit_id == portion.ingredient.unit_id
			if portion.ingredient.unit.short_name
				portion_unit = portion.ingredient.unit.short_name.downcase
			else
				portion_unit = portion.ingredient.unit.name
			end
		else
			correct_unit = portion.unit
			if correct_unit.short_name
				portion_unit = correct_unit.short_name.downcase
			else
				portion_unit = correct_unit.name
			end
		end

		portion_amount = portion.amount
		ingredient = portion.ingredient.name

		if portion_amount == 0.33
			portion_amount = 1/3.to_r
		elsif portion_amount == 0.67
			portion_amount = 2/3.to_r
		end

		if (portion_amount.to_f % 1 == 0)
			portion_amount = portion_amount.to_i
		elsif (portion_amount.to_r > 1)
			# portion_amount = portion.amount.to_r
			portion_amount = portion_amount.to_r.to_whole_fraction
			portion_amount = portion_amount[0].to_s + " <sup>" + portion_amount[1].to_s + "</sup>/<sub>" + portion_amount[2].to_s + "</sub>"
		else
			portion_amount = portion_amount.to_r.to_s
			portion_amount = portion_amount.split('/')
			portion_amount = " <sup>" + portion_amount[0].to_s + "</sup>/<sub>" + portion_amount[1].to_s + "</sub>"
		end


		if portion_unit == "Each"
			## figure out pluralization at same time, based on portion amount
			portion_amount.to_s + ' ' + ingredient.pluralize(portion_amount.to_i)
		else
			pluralize(portion_amount, portion_unit.to_s.titleize) + ' ' + ingredient.to_s
		end
	end

	def cuisines_list()
		return ["American", "British", "Caribbean", "Chinese", "French", "Greek", "Indian", "Italian", "Japanese", "Mediterranean", "Mexican", "Moroccan", "Spanish", "Thai", "Turkish", "Vietnamese"]
	end

	def publishable_state_check(recipe: nil)
		return nil if recipe == nil

		if !recipe.title.blank? &&
				recipe.steps.length > 0 &&
				!recipe.steps.first.content.blank? &&
				recipe.cook_time != nil &&
				recipe.portions.length > 0
			## Recipe is publishable

			return true
		else
			## Recipe is not publishable
			return false
		end
	end

	def recipe_exists_and_can_be_edited(recipe_id: nil, user: nil)
		return nil if recipe_id == nil || user == nil
		if Recipe.exists?(recipe_id.to_f) && (user.admin || user.recipes.map(&:id).include?(recipe_id.to_f))
			return true
		else
			return false
		end
	end

end

app/views/recipes/_old_edit.html.erb
<%= form_for @recipe, html: {class: "form-horizontal"} do |f| %>
  <fieldset id="recipe-meta">
    <ol>
      <li class="control-group">
        <%= f.label :title, "Recipe Name", class: "control-label" %>
        <div class="controls"><%= f.text_field :title %></div>
      </li>
      <li class="control-group">
        <%= f.label :description, "A brief description of this recipe", class: "control-label" %>
        <div class="controls"><%= f.text_area :description, rows: 10 %></div>
      </li>
    </ol>
  </fieldset>

  <fieldset id="recipe-ingredients">
    <ol>
      <%= f.fields_for :portions do |portion| %>
        <%= render 'portion_fields', f: portion %>
      <% end %>
    </ol>
    <%= link_to_add_association 'add ingredient', f, :portions, 'data-association-insertion-node' => "#recipe-ingredients ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|portion| portion.build_ingredient; portion } %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/recipes/_old_new.html.erb
<%= form_for @recipe, html: {class: "form-horizontal"} do |f| %>
  <fieldset id="recipe-meta">
    <ol>
      <li class="control-group">
        <%= f.label :title, "Recipe Name", class: "control-label" %>
        <div class="controls"><%= f.text_field :title %></div>
      </li>
      <li class="control-group">
        <%= f.label :description, "A brief description of this recipe", class: "control-label" %>
        <div class="controls"><%= f.text_area :description, rows: 10 %></div>
      </li>
      <li class="control-group">
        <%= f.label :cuisine, "Recipe Name", class: "control-label" %>
        <%= select_tag :cuisine, options_for_select(@cuisines), prompt: "Pick the cuisine"  %>
      </li>
    </ol>
  </fieldset>

  <fieldset id="recipe-ingredients">
    <ol>
      <%= f.fields_for :portions do |portion| %>
        <%= render 'portion_fields', :f => portion %>
      <% end %>
    </ol>
    <%= link_to_add_association 'add ingredient', f, :portions, 'data-association-insertion-node' => "#recipe-ingredients ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|portion| portion.build_ingredient; portion } %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/recipes/_portion_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <%= f.label :amount, "Amount:" %>
    <%= f.text_field :amount %>

    <%= f.fields_for :ingredient do |portion_ingredient| %>
      <%= portion_ingredient.select :unit_id, Unit.all.collect { |unit| [ unit.name, unit.id ] } %>
			<%= portion_ingredient.select :id, Ingredient.all.collect { |ingredient| [ ingredient.name, ingredient.id ] } %>
    <% end %>

    <%= link_to_remove_association "remove", f %>
  </div>
</li>

app/views/recipes/_recipe_list_partial.html.erb
<%
  require 'uri'
  background_image_url = 'https://source.unsplash.com/500x350/weekly?food'
	if recipe.image_url
    background_image_url = "https://res.cloudinary.com/heo5njalm/image/upload/t_recipe_thumb_size/#{recipe.image_url}"
  elsif recipe.title
    background_image_url = 'https://source.unsplash.com/500x350/weekly?' + URI::encode(recipe.title).to_s.downcase + ',food'
  end
%>

<div class="list_block list_block__column bg-center" style="background-image: url('<%= background_image_url %>')">
	<% if defined?(ingredient_stock_match_decimal) && ingredient_stock_match_decimal != nil && !(ingredient_stock_match_decimal.nan?) %>
		<% percent_in_cupboards = ((defined?(waste_saving_rating)) && waste_saving_rating.to_f != 0.to_f) ? (waste_saving_rating.to_f * 100).round : (ingredient_stock_match_decimal.to_f * 100).round %>
		<div class="list_block--content_start">
			<span class="list_block--progress_bar" style="width: <%= percent_in_cupboards %>%"></span>
			<div class="list_block--content_start--text">
				<% if ingredient_stock_match_decimal == 0 && (!(defined?(waste_saving_rating)) || waste_saving_rating.to_f == 0.to_f) %>
					<%= pluralize(num_needed_ingredients, 'ingredient') %> needed
				<% elsif (!(defined?(waste_saving_rating)) || waste_saving_rating.to_f == 0.to_f) %>
					<%= pluralize(num_stock_ingredients, 'ingredient') %> in stock<% if num_needed_ingredients != 0 %>, <%= num_needed_ingredients.to_s %> needed<% end %>
				<% elsif (defined?(waste_saving_rating)) && waste_saving_rating.to_f != 0.to_f %>
					<%= "%g" % ("%.2f" % percent_in_cupboards.to_f) %>% of recipe ingredients going off in next few days
				<% end %>
			</div>
		</div>
	<% elsif recipe.portions.length == 0 %>
		<div class="list_block--content_start list_block--content_start-warn">
			<div class="list_block--content_start--text">
				Recipe has no ingredients!
			</div>
		</div>
	<% elsif !(recipe.live) %>
		<div class="list_block--content_start list_block--content_start-warn">
			<div class="list_block--content_start--text">
				Recipe still in draft mode!
			</div>
		</div>
	<% end %>
	<div class="list_block--content">
		<div class="list_block--title">
			<h3><%= link_to recipe.title, recipe_path(recipe) %></h3>
			<div class="list_block--action_row">
				<% if user_signed_in? %>
					<% if defined?(recipe_edit_mode) %>
							<%= link_to edit_recipe_path(recipe), class: 'svg-btn', title: 'Edit this recipe' do %>
								<%= icomoon('edit') %>
							<% end %>
					<% else %>
						<% unless current_user.favourites.include?(recipe) %>
							<%= link_to favourite_recipe_path(recipe, type: 'favourite'), class: 'unfavourite svg-btn', title: 'Favourite this recipe', method: :put do %>
								<%= icomoon('heart') %>
							<% end %>
						<% else %>
							<%= link_to favourite_recipe_path(recipe, type: 'unfavourite'), class: 'svg-btn', title: 'Unfavourite this recipe',  method: :put do %>
								<%= icomoon('heart') %>
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
		<% if recipe.portions.length == 0 %>
			<div class="list_block--info_rows">
				<br />
				<p>Not live - only you can see / edit this recipe</p>
				<p>Add ingredients to make this recipe live</p>
			</div>
		<% elsif recipe[:live] == false %>
			<div class="list_block--info_rows">
				<br />
				<p>Not live - not yet published on the site</p>
				<p>Edit the recipe to make it live</p>
				<br />
			</div>
		<% end %>
		<% if recipe.portions.length != 0 %>
			<div class="list_block--info_rows">
				<% if vegan?(recipe) %><p>Vegan &check;</p><% end %>
				<% if vegetarian?(recipe) %><p>Vegetarian &check;</p><% end %>
				<% if gluten_free?(recipe) %><p>Gluten Free &check;</p><% end %>
				<% if dairy_free?(recipe) %><p>Dairy Free &check;</p><% end %>
				<% if kosher?(recipe) %><p>Kosher &check;</p><% end %>
			</div>
		<% end %>
	</div>
	<% if recipe.cuisine && recipe.cuisine.to_s != '' %>
		<div class="list_block--content_end">
			<% if defined?(ingredient_results) && ingredient_results != nil %>
				<%
					search_ingredient_ids = ingredient_results.map(&:id) & recipe.ingredients.map(&:id)
					ingredients_from_search = Ingredient.where(id: search_ingredient_ids)
				%>
				<% if ingredients_from_search.length > 0 %>
					<div class="list_block--tag_bar">
						<% ingredients_from_search.each do |i| %>
							<%= link_to i.name, recipes_path(search: i.name), class: "people_marker people_marker__wide" %>
						<% end %>
					</div>
				<% end %>
			<% end %>
			<div class="list_block--cuisine_bar">
				<p><%= recipe.cuisine %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/recipes/edit.html.erb
<% provide(:title, "Editing Recipe: #{@recipe.title}") %>


<%= form_for @recipe, :html => {class: 'content_rich--wrapper', id: 'recipe_edit'} do |f| %>
	<%= render 'recipe_form_partial', f: f %>
<% end %>

<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>


<script>
	window.encodedRecipeId = '<%= Hashids.new(ENV['RECIPE_ID_SALT']).encode(@recipe.id) %>'
	window.csrfToken = '<%= form_authenticity_token %>'
</script>

app/views/recipes/favourites.html.erb
<% provide(:title, 'Your favourited recipes') %>
<div class="main">
  <div class="list_block--collection--wrap">
    <div class="list_block--collection--sibling">
      <h2>Your favourite recipes</h2>
      <%= link_to "Back to all recipes", recipes_path, class: "list_block--item--action" %>
    </div>
    <%= will_paginate(@fav_recipes) %>
    <div class="list_block--collection list_block--collection__tight">
      <% @fav_recipes.each do |recipe| %>
        <%
          user_recipe_stock_matches = UserRecipeStockMatch.where(user_id: current_user[:id], recipe_id: recipe[:id])
          next if user_recipe_stock_matches.length == 0
          user_recipe_stock_match = user_recipe_stock_matches.first
          ingredient_stock_match_decimal = user_recipe_stock_match[:ingredient_stock_match_decimal]
          num_stock_ingredients = user_recipe_stock_match[:num_stock_ingredients]
          num_needed_ingredients = user_recipe_stock_match[:num_needed_ingredients]
        %>
        <%= render 'recipe_list_partial', recipe: recipe, ingredient_stock_match_decimal: ingredient_stock_match_decimal, num_stock_ingredients: num_stock_ingredients, num_needed_ingredients: num_needed_ingredients  %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<% provide(:title, 'Recipes') %>
<div class="main">
  <div class="list_block--collection--wrap">
    <%= form_tag recipes_path, class: 'flex flex-col pt-8 px-6',  method: :get do %>
      <h1 class="mb-3 text-4xl">Search for recipes</h1>
      <div class="w-full border border-solid border-gray-300 flex items-center p-0 rounded">
        <%= text_field_tag :search, params[:search], class: "flex-grow bordered px-5 h-20 block bg-transparent", placeholder: "what do you fancy? Salsa Verde with Salmon? Stove Top Macaroni and Cheese?", list: "recipe_search_autocomplete_list" %>
        <datalist id="recipe_search_autocomplete_list">
          <% @recipe_search_autocomplete_list.each do |item| %>
            <option value="<%= item %>">
          <% end %>
        </datalist>
        <%= button_tag "Search", name: nil, class: "w-20 h-20 p-5 bg-transparent border-0" do %>
          <%= icomoon('search') %>
        <% end %>
      </div>
    <% end %>
    <div class="mt-5 px-6 mb-8">
      <% if params.has_key?(:search) && !params[:search].blank?  %>
        <p>Showing results for "<%= params[:search] %>". <%= link_to "Clear search", recipes_path, class: "ml-2 underline text-primary-700 hover:text-primary-900" %></p>
      <% end %>
    </div>
    <% if @no_results == true %>
      <div class="mt-5 px-6 mb-8">
        <p>No results found! Maybe try something like <%= link_to 'potato', recipes_path(search: 'potato'), class: "underline text-primary-700 hover:text-primary-900" %> or <%= link_to 'egg', recipes_path(search: 'egg'), class: "underline text-primary-700 hover:text-primary-900" %></p>
      </div>
    <% end %>
      <%= will_paginate(@recipes) %>

    <div class="list_block--collection list_block--collection__tight <% if defined? @mini_progress_on %>mini_progress<% end %>">
    <% @recipes.each do |recipe| %>
        <%
          if user_signed_in?
            user_recipe_stock_matches = UserRecipeStockMatch.where(user_id: current_user[:id], recipe_id: recipe[:id])
            next if user_recipe_stock_matches.length == 0
            user_recipe_stock_match = user_recipe_stock_matches.first
            ingredient_stock_match_decimal = user_recipe_stock_match[:ingredient_stock_match_decimal]
            num_stock_ingredients = user_recipe_stock_match[:num_stock_ingredients]
            num_needed_ingredients = user_recipe_stock_match[:num_needed_ingredients]
          else
            ingredient_stock_match_decimal = nil
            num_stock_ingredients = nil
            num_needed_ingredients = nil
          end
        %>
        <%=
          render 'recipe_list_partial',
          recipe: recipe,
          ingredient_stock_match_decimal: ingredient_stock_match_decimal,
          num_stock_ingredients: num_stock_ingredients,
          num_needed_ingredients: num_needed_ingredients,
          ingredient_results: @ingredient_results
        %>
      <% end %>
    </div>
    <% if @no_results == nil %>
      <%= will_paginate(@recipes) %>
    <% end %>
  </div>
  <div class="list_block--collection--wrap">
    <div class="list_block--collection--sibling list_block--collection--sibling_stack">
      <% if user_signed_in? && current_user.recipes.length > 0 %>
        <h2><%= link_to "Your recipes", your_recipes_path %></h2>
      <% else %>
        <h2>Your recipes</h2>
        <p>Add your first recipe!</p>
      <% end %>
    </div>
    <% if user_signed_in? && current_user.recipes.length > 0 %>
      <div class="list_block--collection list_block--collection__tight">
        <%= link_to new_recipe_path(:anchor => 'recipe_title_container'), class: "list_block list_block--link_first link_block-medium_bold link_block-centered" do %>
          <span>Add a new recipe</span>
        <% end %>
        <% current_user.recipes.order("updated_at desc").limit(8).each do |recipe| %>
          <%= render 'recipe_list_partial', recipe: recipe, recipe_edit_mode: true %>
        <% end %>
      </div>
      <% if current_user.recipes.length > 8 %>
        <div class="list_block--collection--sibling">
          <%= link_to "See all of your recipes", your_recipes_path, class: "list_block--item--action" %>
        </div>
      <% end %>
    <% else %>
      <div class="list_block--collection list_block--collection__tight">
        <%= link_to new_recipe_path(:anchor => 'recipe_title_container'), class: "list_block list_block-wide list_block--link_first link_block-large_bold link_block-centered" do %>
          <span>Add a new recipe</span>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if @fav_recipes.length > 0 %>
    <div class="list_block--collection--wrap">
      <div class="list_block--collection--sibling">
        <h2>Favourited recipes</h2>
      </div>
      <div class="list_block--collection list_block--collection__tight">
        <% if user_signed_in?  %>
          <% @fav_recipes_limit.each do |recipe| %>
            <%
              user_recipe_stock_matches = UserRecipeStockMatch.where(user_id: current_user[:id], recipe_id: recipe[:id])
              next if user_recipe_stock_matches.length == 0
              user_recipe_stock_match = user_recipe_stock_matches.first
              ingredient_stock_match_decimal = user_recipe_stock_match[:ingredient_stock_match_decimal]
              num_stock_ingredients = user_recipe_stock_match[:num_stock_ingredients]
              num_needed_ingredients = user_recipe_stock_match[:num_needed_ingredients]
            %>
            <%= render 'recipe_list_partial', recipe: recipe, ingredient_stock_match_decimal: ingredient_stock_match_decimal, num_stock_ingredients: num_stock_ingredients, num_needed_ingredients: num_needed_ingredients  %>
          <% end %>
        <% end %>
      </div>
      <% if @fav_recipes.length > 6 %>
        <div class="list_block--collection--sibling">
          <%= link_to "See all of your favourited recipes", favourite_recipes_path, class: "list_block--item--action" %>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/recipes/new.html.erb
<% provide(:title, "New Recipe") %>
<%= form_for @recipe, :html => {class: 'content_rich--wrapper', id: 'recipe_edit'} do |f| %>

	<%= render 'recipe_form_partial', f: f %>

<% end %>

<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>

<script>
	window.csrfToken = '<%= form_authenticity_token %>'
</script>

app/views/recipes/yours.html.erb
<% provide(:title, 'Your recipes') %>
<div class="main">
  <div class="list_block--collection--wrap">
    <div class="list_block--collection--sibling">
      <h2>Your recipes</h2>
      <%= link_to "Back to all recipes", recipes_path, class: "list_block--item--action" %>
    </div>
    <%= will_paginate(@recipes) %>
    <div class="list_block--collection list_block--collection__tight">
      <%= link_to new_recipe_path(:anchor => 'recipe_title_container'), class: "list_block list_block-wide list_block--link_first link_block-large_bold link_block-centered" do %>
        <span>Add a new recipe</span>
      <% end %>
      <% @recipes.each do |recipe| %>
        <%= render 'recipe_list_partial', recipe: recipe, recipe_edit_mode: true %>
      <% end %>
    </div>
    <%= will_paginate(@recipes) %>
  </div>
</div>