config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  match '/404', :to => 'errors#not_found', :via => :all, as: :errors_not_found
  match '/500', :to => 'errors#internal_server_error', :via => :all, as: :errors_internal_server_error
  root 'static_pages#home'
  # get '/about' => 'static_pages#about'

  get '/logo', to: 'static_pages#logo'
  get '/cookie-policy', to: 'static_pages#cookie_policy'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/terms-of-use', to: 'static_pages#terms_of_use'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  get '/portions/new' => 'portions#new'
  get '/portions/:id' => 'portions#show', as: :portion
  post '/portions' => 'portions#create'
  post '/portions/new_recipe_portion', to: 'portions#create_from_post'

  get '/stock/new' => 'stocks#new_no_id', as: :stocks_new_no_id
  get '/stock/new/:cupboard_id/custom' => 'stocks#custom_new', as: :stocks_custom_new
  get '/stock/new/:cupboard_id' => 'stocks#new', as: :stocks_new
  get '/stock/picks' => 'stocks#picks'
  get '/stock/:id' => 'stocks#show', as: :stock
  get '/stock/:id/edit' => 'stocks#edit', as: :edit_stock
  get '/stock/delete/:id' => 'stocks#delete_stock', as: :delete_stock
  patch '/stock/:id' => 'stocks#update'
  post '/stock' => 'stocks#create'
  post '/stock/delete' => 'stocks#delete_stock_post'
  post '/stock/custom' => 'stocks#create_custom', as: :create_custom_stock
  post '/stock/toggle_portion' => 'stocks#toggle_shopping_list_portion'
  post '/stock/add_shopping_list' => 'stocks#add_shopping_list'
  post '/stock/new/:cupboard_id' => 'stocks#create', as: :create_stock
  post '/stock/new' => 'stocks#create_with_params', as: :create_stock_with_params
  get '/stock' => 'stocks#index'
  post '/stocks/new_cupboard_stock', to: 'stocks#create_from_post'
  post '/stocks/edit_cupboard_stock', to: 'stocks#update_from_post'

  get '/cupboards' => 'cupboards#index'
  get '/cupboards/demo' => 'cupboards#demo'
  get '/cupboards/new' => 'cupboards#new'
  get '/cupboards/share/:id' => 'cupboards#share', as: :cupboard_share
  get '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite'
  get '/cupboards/:id' => 'cupboards#show'
  post '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite', as: :accept_cupboard_invite
  get '/cupboards/:id/edit' => 'cupboards#edit', as: :edit_cupboard
  patch '/cupboards/:id/edit' => 'cupboards#update'
  post '/cupboards' => 'cupboards#create'
  post '/cupboards/name_update' => 'cupboards#location_update'
  put '/cupboards/:id/delete' => 'cupboards#delete'
  post '/cupboards/autosave_sorting' => 'cupboards#autosave_sorting'
  post '/cupboards/share/:id' => 'cupboards#share_request'
  post '/cupboards/delete_quick_add_stock' => 'cupboards#delete_quick_add_stock'
  post '/cupboards/delete_cupboard_stock' => 'cupboards#delete_cupboard_stock'
  post '/cupboards/delete_cupboard_user' => 'cupboards#delete_cupboard_user'
  post '/cupboards/planner_recipes' => 'cupboards#get_latest_planner_recipes'

  get '/ingredients' => 'ingredients#index'
  get '/ingredients/new' => 'ingredients#new'
  get '/ingredients/:id' => 'ingredients#show', as: :ingredient
  get '/ingredients/:id/edit' => 'ingredients#edit', as: :edit_ingredient
  patch '/ingredients/:id' => 'ingredients#update'
  post '/ingredients' => 'ingredients#create'
  post '/ingredients/default_size_update' => 'ingredient#default_size_update', as: :default_ingredient_size_update

  delete '/demo_logout',   to: 'sessions#demo_logout'

  get '/quick_add_stock/new', to: 'user_fav_stocks#new'
  get '/quick_add_stock/:id/edit', to: 'user_fav_stocks#edit', as: :quick_add_stock_edit

  get '/profile', to: 'users#profile', as: :user_profile
  post '/users/notifications', to: 'users#notifications'
  get '/users', to: 'users#index', as: :user_list

  devise_scope :user do get "/users/sign_out" => "devise/sessions#destroy" end

  # get '/google_login', to: redirect('/auth/google_oauth2')
  # get '/auth/google_oauth2/callback', to: 'users#google_auth'

  post '/feedback/submit' => 'feedback#submit'

  get '/planner', to: 'planner#index', as: :planner
  post '/planner', to: 'planner#refresh', as: :planner_refresh
  get '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  post '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  get '/list/:gen_id', to: 'planner#list', as: :shopping_list_share
  post '/planner/recipe_add', to: 'planner#recipe_add_to_planner'
  post '/planner/recipe_update', to: 'planner#recipe_update_in_planner'
  post '/planner/update_portion', to: 'planner#update_portion'
  post '/planner/recipe_delete', to: 'planner#delete_recipe_from_planner'

  resources :user_fav_stocks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/recipes/portion_delete', to: 'recipes#portion_delete'
  post '/recipes/add_image', to: 'recipes#add_image'
  get '/recipes/favourites', to: 'recipes#favourites', as: :favourite_recipes
  get '/recipes/yours', to: 'recipes#yours', as: :your_recipes
  post '/recipes/update_matches', to: 'recipes#update_recipe_matches'

  resources :recipes do
    member do
      # get 'add_to_shopping_list'
      get 'favourite'
      get 'publish_update', as: 'publish_update'
      get 'delete', as: 'delete'
    end
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	belongs_to :unit, optional: true
	has_many :portions, dependent: :delete_all
	has_many :recipes, through: :portions
	has_many :stocks, dependent: :delete_all
	has_many :cupboards, through: :stocks
	has_many :planner_shopping_list_portions, dependent: :delete_all
	has_many :combi_planner_shopping_list_portions, dependent: :delete_all
	has_one :user_fav_stock, dependent: :delete
	has_many :default_ingredient_sizes, dependent: :delete_all

	validates :name, presence: true, allow_blank: false
	validates_uniqueness_of :name, :case_sensitive => false

	searchkick

  def search_data
    {name: name}
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_user

	include UnitsHelper

	def index
		@ingredients = Ingredient.all
	end
	def show
		@ingredient = Ingredient.find(params[:id])
		@recipes = @ingredient.recipes
		@cupboards = @ingredient.cupboards
		@portions = @ingredient.portions
	end
	def new
    @ingredient = Ingredient.new
		@units = unit_list()
  end
  def create
		ingredient = Ingredient.new(ingredient_params)


    if ingredient.save
			if params.has_key?(:default_ingredient_sizes)
				sizes_hash = params[:default_ingredient_sizes].to_unsafe_h
				sizes_hash.map do |size_id, values|
					if size_id === "new"
						values.each do |value|
							if value["amount"].to_f != 0.0
								ingredient.default_ingredient_sizes.create(
									amount: value["amount"],
									unit_id: value["unit_id"]
								)
							end
						end
					end
				end
			end
			redirect_to ingredients_path(anchor: ingredient.id)
			Ingredient.reindex
    else
      render 'new'
    end
	end
	def edit
		@ingredient = Ingredient.find(params[:id])
		@portions = @ingredient.portions
		@units = unit_list()
	end
	def update
		ingredient = Ingredient.find(params[:id])

		if params.has_key?(:default_ingredient_sizes)
			sizes_hash = params[:default_ingredient_sizes].to_unsafe_h
			sizes_hash.map do |size_id, values|
				if size_id === "new"
					values.each do |value|
						if value["amount"].to_f != 0.0
							ingredient.default_ingredient_sizes.create(
								amount: value["amount"],
								unit_id: value["unit_id"]
							)
						end
					end
				else
					if ingredient.default_ingredient_sizes.where(id: size_id).length > 0
						if values.has_key?("delete") && values["delete"] == "true"
							ingredient.default_ingredient_sizes.where(id: size_id).first.destroy
						else
							ingredient.default_ingredient_sizes.where(id: size_id).first.update_attributes(
								amount: values["amount"],
								unit_id: values["unit_id"]
							)
						end
					end
				end
			end
		end

		if ingredient.update(ingredient_params)
			redirect_to ingredients_path(anchor: ingredient.id)
			Ingredient.reindex
		else
			render 'edit'
		end
	end

	def default_size_update
	end

	protected
		def ingredient_params
			params.require(:ingredient).permit(
				:name,
				:searchable,
				:vegan,
				:vegetarian,
				:gluten_free,
				:dairy_free,
				:kosher,
				:use_by_date_diff
			)
		end

		# Confirms an admin user.
		def admin_user
			if current_user.admin == false
				flash[:notice] = "Only admins can edit ingredients directly"
				redirect_to(root_path)
			end
		end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper

	def convert_serving_to_hash(serving = nil)
		return if serving == nil
		return serving if serving.class == Hash
		return {
			amount: serving.amount ? serving.amount.to_f : nil,
			unit: serving.unit
		}
	end

	def convert_serving_array_to_array_of_hashes(serving_array)
		return convert_serving_to_hash(serving_array.first) if serving_array.length == 1
		return false unless serving_array.length > 1
		processed_serving_array = []
		serving_array.map{|i| processed_serving_array.push(convert_serving_to_hash(i))}
		return false if processed_serving_array.select{|i| i[:unit] == nil || i[:amount] == nil }.length > 0
		return processed_serving_array
	end

	def convert_to_different_unit(serving = nil, unit_to_convert_to = nil)
		return if serving == nil || unit_to_convert_to == nil

		processed_serving = convert_serving_to_hash(serving)
		return if processed_serving[:unit] == nil || processed_serving[:amount] == nil

		return {
			amount: processed_serving[:amount] / unit_to_convert_to.metric_ratio,
			unit: unit_to_convert_to
		}
	end


	def get_serving_unit_type(serving)
		if serving.class != Hash
			serving = convert_serving_to_hash(serving)
		end

		return serving[:unit].unit_type
	end

	def ingredient_metric_check(serving)
		if serving.class != Hash
			serving = convert_serving_to_hash(serving)
		end

		return false if serving[:unit].metric_ratio == nil
		return serving
	end

	def ingredient_unit_type_match(serving_array = [])
		processed_serving_array = convert_serving_array_to_array_of_hashes(serving_array)
		return false if processed_serving_array == false

		unit_types = processed_serving_array.map{|i| i[:unit].unit_type}.uniq
		return false if unit_types.length > 1

		return unit_types.first
	end

	def serving_converter(serving = nil)
		## serving means either stock or portion
		## or anything which has an ingredient association and an amount

		return false if serving == nil
		processed_serving = convert_serving_to_hash(serving)
		return false if (processed_serving[:unit] == nil || processed_serving[:amount] == nil)

		if processed_serving[:unit].unit_type != nil
			return {
				amount: processed_serving[:amount].to_f * processed_serving[:unit].metric_ratio.to_f,
				unit: default_unit(processed_serving)
			}
		else
			return processed_serving
		end

	end

	def serving_difference(serving_array = [])

		return serving_converter(serving_array.first) if serving_array.length == 1
		return false unless serving_array.length > 1

		### the order in this array matters so can't take more than two servings
		### the first serving will be what the other serving amount gets taken from
		return false if serving_array.length > 2

		unit_type = ingredient_unit_type_match(serving_array)
		return false if unit_type == false

		processed_serving_array = convert_serving_array_to_array_of_hashes(serving_array)
		return false if processed_serving_array == false

		unit_types = processed_serving_array.map{|i| i[:unit].unit_type}.uniq
		return false if unit_types.length > 1

		processed_serving_array = processed_serving_array.map{|s| serving_converter(s)}
		# processed_serving_array = processed_serving_array.sort{|a, b| a[:amount] <=> b[:amount]}.reverse

		serving_diff_amount = processed_serving_array.first[:amount]
		processed_serving_array.each_with_index.map{|s, i| next if i == 0; serving_diff_amount = serving_diff_amount - s[:amount] }.compact

		serving_diff = processed_serving_array.first
		serving_diff[:amount] = serving_diff_amount

		return serving_diff

	end

	def serving_addition(serving_array = [])
		return serving_converter(serving_array.first) if serving_array.length == 1
		return false unless serving_array.length > 1

		unit_type = ingredient_unit_type_match(serving_array)
		return false if unit_type == false

		processed_serving_array = convert_serving_array_to_array_of_hashes(serving_array)
		return false if processed_serving_array == false

		unit_types = processed_serving_array.map{|i| i[:unit].unit_type}.uniq
		return false if unit_types.length > 1

		unit_ids = processed_serving_array.map{|i| i[:unit]}.uniq
		if unit_ids.length > 1
			processed_serving_array = processed_serving_array.map{|s| serving_converter(s)}
		end

		return {
			amount: processed_serving_array.select{|s| s.key?(:amount) && s[:amount] != nil}.sum{|s| s[:amount] },
			unit: processed_serving_array.first[:unit]
		}

	end

	def default_unit(serving = nil)
		return unless serving != nil
		return unless ingredient_metric_check(serving) || get_serving_unit_type(serving)

		return Unit.find_by(unit_type: get_serving_unit_type(serving), metric_ratio: 1)
	end

	def default_unit_id(serving = nil)
		return unless serving != nil

		return default_unit(serving).id

	end

	def find_planner_portion_size(serving = nil)
		return unless serving != nil

		converted_sizes = []
		sizes = serving.ingredient.default_ingredient_sizes
		return false if sizes.length == 0
		sizes.map{|s| converted_sizes.push(convert_serving_to_hash(s))}
		converted_serving = convert_serving_to_hash(serving)

		return false if ingredient_unit_type_match([converted_serving, converted_sizes.first]) == false


		100.times.each_with_index do |i, index|
			next if index == 0
			sizes.each do |s|
				converted_size = convert_serving_to_hash(s)
				converted_size[:amount] = converted_size[:amount] * index
				size_diff = serving_difference([converted_size, converted_serving])
				if size_diff != false && size_diff[:amount] >= 0
					return {
						original_ingredient_size: s,
						converted_size: converted_size
					}
				end

			end
		end

	end

	def get_ingredient_use_by_date_diff(ing = nil)
		return 14 if ing == nil

		if ing.default_ingredient_sizes && ing.default_ingredient_sizes.length > 0
			return ing.default_ingredient_sizes.sort{|a,b| b.use_by_date_diff <=> a.use_by_date_diff}.first.use_by_date_diff
		end

		return 14
	end

	def ingredient_list()
		return Ingredient.all.order('name ASC').reject{|i| i.name == ''}
	end

end

app/views/ingredients/_form_partial.html.erb
<div class="item_form--wrapper">
	<%= form_for ingredient, :html => {id: "ingredient_form", class: "item_form"} do |i| %>
		<div class="item_form--title">
			<h1 class="pr-0"><%= i.text_field :name, value: ingredient.name, class: "w-full pl-2" %></h1>
		</div>
		<div class="item_form--contents">

			<div class="item_form--content_row">
				<h3>Dietary details</h3>

				<%= i.check_box :vegan, {id: "vegan_check", style: "display:none", checked: ingredient.vegan}, "true", "false" %>
				<%= label_tag "vegan_check", "Vegan", class: "fancy_checkbox_label" %>

				<%= i.check_box :vegetarian, {id: "vegetarian_check", style: "display:none", checked: ingredient.vegetarian}, "true", "false" %>
				<%= label_tag "vegetarian_check", "Vegetarian", class: "fancy_checkbox_label" %>

				<%= i.check_box :gluten_free, {id: "gluten_free_check", style: "display:none", checked: ingredient.gluten_free}, "true", "false" %>
				<%= label_tag "gluten_free_check", "Gluten Free", class: "fancy_checkbox_label" %>

				<%= i.check_box :dairy_free, {id: "dairy_free_check", style: "display:none", checked: ingredient.dairy_free}, "true", "false" %>
				<%= label_tag "dairy_free_check", "Dairy Free", class: "fancy_checkbox_label" %>

				<%= i.check_box :kosher, {id: "kosher_check", style: "display:none", checked: ingredient.kosher}, "true", "false" %>
				<%= label_tag "kosher_check", "Kosher", class: "fancy_checkbox_label" %>

			</div>
			<div class="my-3">
				<p>Usually fresh for (this number of days):</p>
				<%= i.number_field :use_by_date_diff, {value: (ingredient.use_by_date_diff == 0 ? 14 : ingredient.use_by_date_diff), class: "px-2 py-3 mt-2"} %>
			</div>
			<div class="item_form--content_row">
				<h3>Default sizes</h3>

				<ul style="width: 100%;">
					<% if ingredient.default_ingredient_sizes.length > 0 %>
						<% ingredient.default_ingredient_sizes.each do |size| %>
							<li style="display:flex;margin-bottom:1.2rem;" id="<%= size.id %>">
								<%= number_field_tag "default_ingredient_sizes[#{size.id}][amount]", size.amount, style: "padding-left:.5rem" %>
								<div style="flex-grow:1; margin-left:.9rem">
									<%= select_tag "default_ingredient_sizes[#{size.id}][unit_id]", options_for_select(unit_list().collect{|u| [u[:name], u[:id]] }, selected: (size.unit_id ? size.unit_id : nil)), class: "choices--basis half_width" %>
								</div>
								<span class="ingredient_size_delete_btn"
									style="padding: 1rem;
												display: flex;
												align-items: center;
												justify-content: center;
												position: relative;
												margin-left: 0.7rem;
												background-color: white;
												border: 1px solid #49a99f;
												cursor: pointer;
												border-radius: 3px;"
								><svg style="height: 1.4rem;width: 1.4rem;fill: currentColor;margin:0;"><use xlink:href="<%= svg_icon_path("close") %>"></use></svg></span>
							</li>
						<% end %>
					<% end %>
					<li style="display:none;margin-bottom:1.2rem;" class="row_for_cloning">
						<%= number_field_tag "default_ingredient_sizes[new][][amount]", nil, style: "padding-left:.5rem" %>
						<div style="flex-grow:1; margin-left:.9rem">
							<%= select_tag "default_ingredient_sizes[new][][unit_id]", options_for_select(unit_list().collect{|u| [u[:name], u[:id]] }), class: "half_width" %>
						</div>
						<span class="cloned_ingredient_size_delete_btn"
									style="padding: 1rem;
												display: flex;
												align-items: center;
												justify-content: center;
												position: relative;
												margin-left: 0.9rem;
												background-color: white;
												border: 1px solid #49a99f;
												cursor: pointer;
												border-radius: 3px;"
								><svg style="height: 1.4rem;width: 1.4rem;fill: currentColor;margin:0;"><use xlink:href="<%= svg_icon_path("close") %>"></use></svg></span>
					</li>
					<li style="display:flex;margin-bottom:1.2rem;justify-content:flex-end" class="new_size_button_row">
						<span id="new_size_button"
								style="background: white;
											border: 1px solid #93dbd7;
											font-size: 1.4rem;
											font-family: Lato;
											padding: 1rem 1rem;
											border-radius: .3rem;
											cursor:pointer;">Add new default ingredient size</span>
					</li>
				</ul>
			</div>

			<div class="item_form--content_row">
				<%= i.button "Save" %>
			</div>
		</div>
	<% end %>
</div>

app/views/ingredients/edit.html.erb
<% provide(:title, "Editing #{@ingredient.name}") %>

<%= render 'form_partial', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<div class="main ingredient-index">
  <div class="standard-wrapper">
    <div class="list_block--collection--wrap">
      <div class="list_block--collection--sibling">
        <h1>Ingredients list</h1>
        <br />
        <%= link_to 'New Ingredient', ingredients_new_path %>
      </div>
      <div class="flex flex-wrap">
        <% @ingredients.order(updated_at: :desc).each do |ingredient| %>
          <div class="p-2 w-1/2 lg:w-1/4 flex">
            <%= link_to edit_ingredient_path(ingredient),
                class: "flex flex-wrap p-3
                        border border-solid border-primary-400
                        text-base w-full content-start
                        hover:bg-primary-100
                        target:shadow-outline
                        rounded",
                id: ingredient.id do %>
              <h3 class="w-full mb-2 text-2xl"><%= ingredient.name %></h3>
              <div class="w-full">
                <p class="text-base">Fresh for <%= ingredient.use_by_date_diff %> days</p>
              </div>
              <div class="w-full">
                <h4 class="text-lg mt-3 mb-1">Default sizes</h4>
                <% if ingredient.default_ingredient_sizes.length > 0 %>
                  <ul style="width: 100%;list-style: circle;padding-left: 2em;">
                    <% ingredient.default_ingredient_sizes.each do |size| %>
                      <li>
                        <p class="text-base"><%= short_serving_size(size) %></p>
                      </li>
                    <% end %>
                  </ul>
                <% else %>
                  <p class="w-full italic text-base">No ingredient sizes</p>
                <% end %>
                <div class="w-full">
                  <h4 class="text-lg mt-3 mb-1">Dietary details</h4>
                  <p class="w-full text-base">
                    [
                      <%= ingredient.vegan == true ? 'Vegan, ' : '' %>
                      <%= ingredient.vegetarian == true ? 'Vegetarian, ' : '' %>
                      <%= ingredient.dairy_free == true ? 'Dairy free, ' : '' %>
                      <%= ingredient.gluten_free == true ? 'Gluten free, ' : '' %>
                      <%= ingredient.kosher == true ? 'Kosher' : '' %>
                    ]
                  </p>
                </div>
              </div>
            <% end %>
          </div>

        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<% provide(:title, "Creating a new ingredient") %>

<%= render 'form_partial', ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<div class="main ingredient-show">
  <div class="standard-wrapper">

    <!-- Display an ingredient's info here -->
    <div class="ingredient">

      <div class="info">
        <h3 class="ingredient-name"><%= @ingredient.name %></h3>
        <%= link_to "Edit Ingredient", edit_ingredient_path(@ingredient) %>
      </div>
    </div>

    <br />
    <br />
    <br />

    <% if @recipes.first %>
      <h2>recipes</h2>
      <!-- Display each recipe's info here -->
      <% @recipes.each do |recipe| %>
      <div class="recipe">

        <h3 class="recipe-title"><%= recipe.title %></h3>
        <%= link_to "Learn more", recipe_path(recipe) %>
      </div>
      <% end %>
    <% else %>
      <p>Ingredient not used in any recipes. Check out <%= link_to "all recipes", recipes_path %>.</p>
    <% end %>

    <br />
    <br />
    <br />

    <% if @cupboards.first %>
      <h2>Cupboard</h2>
      <!-- Display each location's info here -->
      <% @cupboards.each do |cupboard| %>
      <div class="recipe">
        <h3 class="cupboard-location"><%= cupboard.location %></h3>
        <%= link_to "Learn more", cupboard_path(cupboard) %>
      </div>
      <% end %>
    <% else %>
      <p>Ingredient not currently in stock. Check everything <%= link_to "currently in stock", cupboards_path %>.</p>
    <% end %>

  </div>
</div>