config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  match '/404', :to => 'errors#not_found', :via => :all, as: :errors_not_found
  match '/500', :to => 'errors#internal_server_error', :via => :all, as: :errors_internal_server_error
  root 'static_pages#home'
  # get '/about' => 'static_pages#about'

  get '/logo', to: 'static_pages#logo'
  get '/cookie-policy', to: 'static_pages#cookie_policy'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/terms-of-use', to: 'static_pages#terms_of_use'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  get '/portions/new' => 'portions#new'
  get '/portions/:id' => 'portions#show', as: :portion
  post '/portions' => 'portions#create'
  post '/portions/new_recipe_portion', to: 'portions#create_from_post'

  get '/stock/new' => 'stocks#new_no_id', as: :stocks_new_no_id
  get '/stock/new/:cupboard_id/custom' => 'stocks#custom_new', as: :stocks_custom_new
  get '/stock/new/:cupboard_id' => 'stocks#new', as: :stocks_new
  get '/stock/picks' => 'stocks#picks'
  get '/stock/:id' => 'stocks#show', as: :stock
  get '/stock/:id/edit' => 'stocks#edit', as: :edit_stock
  get '/stock/delete/:id' => 'stocks#delete_stock', as: :delete_stock
  patch '/stock/:id' => 'stocks#update'
  post '/stock' => 'stocks#create'
  post '/stock/delete' => 'stocks#delete_stock_post'
  post '/stock/custom' => 'stocks#create_custom', as: :create_custom_stock
  post '/stock/toggle_portion' => 'stocks#toggle_shopping_list_portion'
  post '/stock/add_shopping_list' => 'stocks#add_shopping_list'
  post '/stock/new/:cupboard_id' => 'stocks#create', as: :create_stock
  post '/stock/new' => 'stocks#create_with_params', as: :create_stock_with_params
  get '/stock' => 'stocks#index'
  post '/stocks/new_cupboard_stock', to: 'stocks#create_from_post'
  post '/stocks/edit_cupboard_stock', to: 'stocks#update_from_post'

  get '/cupboards' => 'cupboards#index'
  get '/cupboards/demo' => 'cupboards#demo'
  get '/cupboards/new' => 'cupboards#new'
  get '/cupboards/share/:id' => 'cupboards#share', as: :cupboard_share
  get '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite'
  get '/cupboards/:id' => 'cupboards#show'
  post '/cupboards/accept_cupboard_invite' => 'cupboards#accept_cupboard_invite', as: :accept_cupboard_invite
  get '/cupboards/:id/edit' => 'cupboards#edit', as: :edit_cupboard
  patch '/cupboards/:id/edit' => 'cupboards#update'
  post '/cupboards' => 'cupboards#create'
  post '/cupboards/name_update' => 'cupboards#location_update'
  put '/cupboards/:id/delete' => 'cupboards#delete'
  post '/cupboards/autosave_sorting' => 'cupboards#autosave_sorting'
  post '/cupboards/share/:id' => 'cupboards#share_request'
  post '/cupboards/delete_quick_add_stock' => 'cupboards#delete_quick_add_stock'
  post '/cupboards/delete_cupboard_stock' => 'cupboards#delete_cupboard_stock'
  post '/cupboards/delete_cupboard_user' => 'cupboards#delete_cupboard_user'
  post '/cupboards/planner_recipes' => 'cupboards#get_latest_planner_recipes'

  get '/ingredients' => 'ingredients#index'
  get '/ingredients/new' => 'ingredients#new'
  get '/ingredients/:id' => 'ingredients#show', as: :ingredient
  get '/ingredients/:id/edit' => 'ingredients#edit', as: :edit_ingredient
  patch '/ingredients/:id' => 'ingredients#update'
  post '/ingredients' => 'ingredients#create'
  post '/ingredients/default_size_update' => 'ingredient#default_size_update', as: :default_ingredient_size_update

  delete '/demo_logout',   to: 'sessions#demo_logout'

  get '/quick_add_stock/new', to: 'user_fav_stocks#new'
  get '/quick_add_stock/:id/edit', to: 'user_fav_stocks#edit', as: :quick_add_stock_edit

  get '/profile', to: 'users#profile', as: :user_profile
  post '/users/notifications', to: 'users#notifications'
  get '/users', to: 'users#index', as: :user_list

  devise_scope :user do get "/users/sign_out" => "devise/sessions#destroy" end

  # get '/google_login', to: redirect('/auth/google_oauth2')
  # get '/auth/google_oauth2/callback', to: 'users#google_auth'

  post '/feedback/submit' => 'feedback#submit'

  get '/planner', to: 'planner#index', as: :planner
  post '/planner', to: 'planner#refresh', as: :planner_refresh
  get '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  post '/planner/shopping_list', to: 'planner#get_shopping_list_content'
  get '/list/:gen_id', to: 'planner#list', as: :shopping_list_share
  post '/planner/recipe_add', to: 'planner#recipe_add_to_planner'
  post '/planner/recipe_update', to: 'planner#recipe_update_in_planner'
  post '/planner/update_portion', to: 'planner#update_portion'
  post '/planner/recipe_delete', to: 'planner#delete_recipe_from_planner'

  resources :user_fav_stocks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/recipes/portion_delete', to: 'recipes#portion_delete'
  post '/recipes/add_image', to: 'recipes#add_image'
  get '/recipes/favourites', to: 'recipes#favourites', as: :favourite_recipes
  get '/recipes/yours', to: 'recipes#yours', as: :your_recipes
  post '/recipes/update_matches', to: 'recipes#update_recipe_matches'

  resources :recipes do
    member do
      # get 'add_to_shopping_list'
      get 'favourite'
      get 'publish_update', as: 'publish_update'
      get 'delete', as: 'delete'
    end
  end
end

app/models/cupboard.rb
class Cupboard < ApplicationRecord
	has_many :stocks, dependent: :delete_all
	has_many :ingredients, through: :stocks

	has_many :cupboard_users,  dependent: :delete_all
	has_many :users, through: :cupboard_users

	accepts_nested_attributes_for :stocks,
					:reject_if => :all_blank,
					:allow_destroy => true
	accepts_nested_attributes_for :ingredients

	validates :location, presence: true
end

app/helpers/cupboard_helper.rb
module CupboardHelper
	def use_by_date_string(stock)
		days_from_now = (stock.use_by_date - Date.current).to_i
		weeks_from_now = (days_from_now / 7).floor
		months_from_now = (days_from_now / 30).floor
		if stock.use_by_date.today?
			return "Going out of date today!"
		elsif stock.use_by_date.future?
			if days_from_now > 30
				return "Use by date is more than " + pluralize(months_from_now, "month") + " away"
			elsif days_from_now > 6
				return "Use by date is more than " + pluralize(weeks_from_now, "week") + " away"
			else
				return "Use by date is " + pluralize(days_from_now, "day") + " away"
			end
		elsif days_from_now > -2
			return "Just out of date"
		else
			return "Out of date"
		end
	end
	def date_warning_class(stock)
		days_from_now = (stock.use_by_date - Date.current).to_i
		if days_from_now < 2 && days_from_now > -2
			return ' date-part-warning'
		elsif days_from_now <= -2
			return ' date-full-warning'
		end
	end
	def stock_unit(stock)
		return stock.unit
	end
	def cupboard_shared_class(cupboard)
		if cupboard.cupboard_users.length > 1
			return 'shared'
		end
	end
	def cupboard_empty_class(cupboard)
		stock_num = cupboard.stocks.select{|s| s.planner_recipe == nil && s.hidden == false && s.ingredient.name.downcase.to_s != "water" && s.use_by_date > Date.current - stock_date_limit.day}.length
		if stock_num < 1
			return 'empty'
		end
	end
	def cupboard_stocks_selection_in_date(cupboard)
		stocks = cupboard.stocks.select{|s| s.planner_shopping_list_portion_id == nil && s.hidden == false && s.ingredient.name.downcase != 'water' && s.use_by_date > Date.current - stock_date_limit.day}.sort_by{|s| [s.use_by_date, s.ingredient.name]}
		return stocks
	end
	def planner_stocks(planner_recipe)
		stock_from_planner_portions = planner_recipe.planner_shopping_list_portions
			.map{|p| p.stock}.compact
			.select{|s|s.hidden == false && s.always_available == false && s.use_by_date > Date.current - stock_date_limit.day}
			.sort_by{|s| s.use_by_date}
		return stock_from_planner_portions
	end

	def user_cupboards(user = nil)
		return if user == nil
		return user.cupboard_users.where(accepted: true)
			.select{|cu| cu.cupboard.setup == false && cu.cupboard.hidden == false }
			.map{|cu| cu.cupboard }.sort_by{|c| c.created_at}.reverse!
	end

	def first_cupboard(user = nil)
		return user_cupboards(user).first
	end


	def user_stock(user = nil, showPlannerPortionStock = false)
		return if user == nil

		cupboards = user_cupboards(user)

		if showPlannerPortionStock
			user_stock = user.stocks
				.where(cupboard_id: cupboards.map(&:id), hidden: false)
				.uniq
		else
			user_stock = user.stocks
				.where(cupboard_id: cupboards.map(&:id), planner_shopping_list_portion_id: nil, hidden: false)
				.uniq
		end


		return user_stock
	end

	def user_stock_multiples(user = nil)
		return if user == nil

		user_stock_multiples = user_stock(user)
			.group_by{|s|s.ingredient_id}.select{|i_id, v| v.length > 1 }.values.flatten

		return user_stock_multiples
	end

	def needed_stock(planner_recipe)
		planner_stock_ingredient_ids = planner_stocks(planner_recipe).map(&:ingredient_id).uniq
		return planner_recipe.recipe.portions.where.not(ingredient_id: planner_stock_ingredient_ids)
	end

	def recipe_portions_checked_portions(planner_recipe)
		return {
			recipe_portions_in_stock: planner_stocks(planner_recipe).length,
			recipe_portion_total: planner_recipe.recipe.portions.select{|p|p.ingredient.name.downcase != 'water'}.length
		}
	end

	def recipe_portions_in_stock_vs_total_float(planner_recipe)
		recipe_portions_checked_portions_hash = recipe_portions_checked_portions(planner_recipe)
		return recipe_portions_checked_portions_hash[:recipe_portions_in_stock] / recipe_portions_checked_portions_hash[:recipe_portion_total].to_f
	end

	def recipe_portions_in_stock_vs_total_percentage(planner_recipe)
		return recipe_portions_in_stock_vs_total_float(planner_recipe) * 100
	end


	def processed_cupboard_contents(user = nil)
		return [] if user == nil
		cupboard_id_hashids = Hashids.new(ENV['CUPBOARDS_ID_SALT'])
		cupboard_sharing_hashids = Hashids.new(ENV['CUPBOARD_SHARING_ID_SALT'])
		delete_stock_hashids = Hashids.new(ENV['DELETE_STOCK_ID_SALT'])

		cupboards = user_cupboards(current_user)
		return cupboards.map{|c| {
			title: c.location,
			id: cupboard_id_hashids.encode(c.id),
			stock: cupboard_stocks_selection_in_date(c).length > 0 ? cupboard_stocks_selection_in_date(c).map{|s|
				{
					id: s.id,
					title: serving_description(s),
					href: edit_stock_path(s),
					fresh: s.use_by_date >= Time.zone.now,
					freshForTime: distance_of_time_in_words(Time.zone.now, s.use_by_date),
					encodedIdForDelete: delete_stock_hashids.encode(s.id)
				}
			} : [],
			newStockHref: stocks_new_path(cupboard_id: cupboard_id_hashids.encode(c.id)),
			customNewStockHref: stocks_custom_new_path(cupboard_id: cupboard_id_hashids.encode(c.id)),
			users: c.cupboard_users.select{|cu|cu.user != current_user}.length > 0 ? c.cupboard_users.select{|cu|cu.user != current_user}.map{|cu|cu.user.name}.to_sentence : nil,
			sharingPath: cupboard_share_path(cupboard_sharing_hashids.encode(c.id))
		}}
	end

	def user_can_access_cupboard(user: nil, cupboard_id: nil)
		return false if (user == nil || cupboard_id == nil)

		return user_cupboards(user).map(&:id).include?(cupboard_id)
	end
end

app/views/cupboards/partials/_index_core.html.erb
<% if planner_recipes.length > 0 %>
  <div class="py-8 border-b border-solid border-gray-500">
    <div class="px-6 flex flex-wrap py-4">
      <h2 class="w-full text-lg mb-2">Planner Recipes</h2>
      <div class="w-full">
        <p class="w-full text-gray-700 flex items-center text-base"><span class="flex w-5 h-5 mr-2"><%= icomoon('information-outline')%></span> Here are the upcoming recipes from your planner</p>
        <p class="w-full text-gray-700 text-base">Checked off shopping list items will be shown here</p>
      </div>
    </div>
    <div class="flex flex-wrap p-4">
      <% planner_recipes.each do |p_recipe| %>
        <div class="flex p-2 flex-grow w-full md:w-1/2 lg:w-1/3">
          <div class="w-full rounded content-between flex flex-col border border-solid border-primary-400">

            <div class="flex flex-wrap pt-4 px-2 pb-10">
              <div class="w-full mx-1 mb-4 non_sortable flex items-center">
                <h3><%= link_to p_recipe.recipe.title, recipe_path(p_recipe.recipe) %> (<%= p_recipe.date.to_s(:short) %>) [<%= recipe_portions_checked_portions(p_recipe)[:recipe_portions_in_stock] %>/<%= recipe_portions_checked_portions(p_recipe)[:recipe_portion_total] %> in stock]</h3>
              </div>
              <% planner_stocks(p_recipe).each do |stock| %>
                <% out_of_date_sentence = 'out of date' + (stock.use_by_date > Time.zone.now ? ' in ' : ' ') + (distance_of_time_in_words(Time.zone.now, stock.use_by_date)) + (stock.use_by_date <= Time.zone.now ? ' ago': '') %>
                <div class="max-w-md flex p-1 w-1/2 sm:w-1/3 non_sortable
                          <% if planner_recipes.length > 1 %>
                            md:w-1/2 lg:w-1/3
                          <% else %>
                            md:w-1/4 lg:w-1/5
                          <% end %>">
                  <div class="flex flex-col w-full items-start rounded bg-primary-400 hover:bg-primary-300 focus:bg-primary-300 overflow-hidden" style="min-height: 8rem;">
                    <span class="w-full h-4 bg-primary-100 flex"><span class="bg-primary-600 h-full" style="width: <%= percentage_of_portion_in_stock(stock) %>%"></span></span>
                    <%= link_to ((stock.users.length == 0 || stock.users.map(&:id).include?(current_user[:id])) ? edit_stock_path(stock.id) : ''),
                        class: "p-3 w-full flex-grow flex flex-col justify-between", title: "#{stock.ingredient.name} - #{out_of_date_sentence}" do %>
                      <p class="text-base mb-2"><%= serving_description(stock.planner_shopping_list_portion) %></p>
                      <span class="w-full text-sm text-gray-700">Fresh for <%= distance_of_time_in_words(Time.zone.now, stock.use_by_date) + (stock.use_by_date <= Time.zone.now ? ' ago': '')%></span>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <% needed_stock(p_recipe).each do |stock| %>
                <div class="max-w-md flex p-1 w-1/2 sm:w-1/3 non_sortable
                            <% if planner_recipes.length > 1 %>
                              md:w-1/2 lg:w-1/3
                            <% else %>
                              md:w-1/4 lg:w-1/5
                            <% end %>">
                  <span class="w-full p-3 rounded bg-primary-200 overflow-hidden cursor-not-allowed non_sortable"
                        style="min-height: 8rem;"
                        title="Not yet in cupboards">
                    <p class="w-full mb-2 italic text-gray-600 text-sm">Need to buy</p>
                    <p class="w-full text-base text-gray-700"><%= serving_description(stock) %></p>
                  </span>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class="mb-4 py-6">
  <div class="px-6 flex justify-center items-center flex-col py-4 text-center">
    <h2 class="text-2xl mb-4">Your Cupboards</h2>
    <button class="js-modal font-sans text-base border border-primary-400 border-solid text-black no-underline rounded
    hover:bg-primary-100 focus:bg-primary-100 p-2 bg-white"
      data-modal-content-id="demo"
      data-modal-title="Quick demo on how to add ingredients"
      data-modal-close-img="<%= png_icon_path('close') %>">How to use</button>
    <%= link_to "How to use", cupboards_demo_path,
        class: "no-js-modal-link text-base border border-primary-400 border-solid text-black no-underline rounded
                hover:bg-primary-100 focus:bg-primary-100 p-2 inline-block"
      %>
  </div>
  <div id="cupboard-list" class="flex flex-wrap p-4">
    <% user_cupboards(current_user).each do |cupboard| %>
      <div class="flex p-2 flex-grow w-full md:w-1/2">
        <div class="cupboard w-full rounded content-between flex flex-col border border-solid border-primary-400 relative"
            style="min-height: 8rem;"
            data-name="cupboard"
            id="<%= cupboard_id_hashids.encode(cupboard.id) %>">
          <div class="flex flex-wrap pt-4 px-2 pb-10"
            data-name="cupboard-sortable"
            data-cupboard-users="<%= cupboard_users_hashids.encode(cupboard.cupboard_users.map(&:user_id).sort!) %>"
            data-cupboard-id="<%= cupboard_id_hashids.encode(cupboard.id) %>">
            <% if cupboard.cupboard_users.length > 1 %>
              <div class="list_block--title_note">SHARED CUPBOARD</div>
            <% end %>
            <div class="w-full mx-1 mb-4 non_sortable flex items-center">
              <h3 class="w-full">
                <%= hidden_field_tag "cupboard_id", cupboard.id %>
                <%= text_field_tag "cupboard_location_#{cupboard.id}", cupboard.location,
                {
                  readonly: cupboard.cupboard_users.where(owner: true).first.user != current_user,
                  title: cupboard.cupboard_users.where(owner: true).first.user != current_user ? "Only the owner can edit a cupboard's name" : nil,
                  class: "w-full transition-all ease duration-300 text-xl border-b border-solid border-primary-300 hover:bg-primary-50 py-1 hover:pl-2 focus:bg-primary-200 focus:pl-2 focus:border-primary-500"
                } %>
              </h3>
              <% if cupboard_stocks_selection_in_date(cupboard).length == 0 && cupboards.length > 1 && cupboard.cupboard_users.where(owner: true).first.user == current_user %>
                <span class="border border-solid border-primary-400 hover:bg-primary-100 rounded flex w-10 h-10 p-2 ml-2"
                  data-name="delete-cupboard-btn">
                  <%= icomoon('bin') %>
                </span>
              <% end %>
            </div>
            <% if cupboard.stocks.first %>
              <% cupboard_stocks_selection_in_date(cupboard).each do |stock| %>
                <% out_of_date_sentence = 'out of date' + (stock.use_by_date > Time.zone.now ? ' in ' : ' ') + (distance_of_time_in_words(Time.zone.now, stock.use_by_date)) + (stock.use_by_date <= Time.zone.now ? ' ago': '') %>
                <div
                  class="sortable max-w-lg flex p-1 w-1/2 sm:w-1/3
                  <% if user_cupboards(current_user).length > 1 %>
                    md:w-1/2 lg:w-1/3 xl:w-1/4
                  <% else %>
                    md:w-1/4 lg:w-1/5 xl:w-1/6
                  <% end %>"
                  data-sortable
                  style="min-height: 8rem;"
                  id="<%= stock.id %>">
                  <%= link_to ((cupboard.communal == false || stock.users.length == 0 || stock.users.map(&:id).include?(current_user[:id])) ? edit_stock_path(stock.id) : ''),
                      class: "flex flex-wrap w-full items-start rounded p-3 border border-solid border-primary-400 bg-primary-400 hover:bg-primary-300 focus:bg-primary-300 list_block--item_show#{date_warning_class(stock)} stock_#{stock.id} #{(cupboard.communal == false || stock.users.length == 0 || stock.users.map(&:id).include?(current_user[:id])) ? '' : 'list_block--item-disabled'}",
                      data: {
                        cupboard_id: "#{cupboard.id}",
                        stock_id:"#{stock.id}",
                        name: "stock"
                      }, title: "#{stock.ingredient.name} - #{out_of_date_sentence}" do %>
                    <span class="flex justify-between w-full">
                      <span class="mr-2">
                        <p class="text-base" data-name="stock-description"><%= serving_description(stock) %></p>
                        <% if cupboard.communal && stock.users.length > 0 %>
                        <p class="text-xs text-gray-800 mt-2">Owner - <%= stock.users.first.name%></p>
                        <% end %>
                      </span>
                      <span class="ml-auto bg-white hover:bg-primary-100 rounded border-0 flex w-10 h-10 p-2 flex-shrink-0"
                            id="<%= delete_stock_hashids.encode(stock.id) %>"
                            data-name="delete-stock-btn">
                        <%= icomoon('bin') %>
                      </span>
                    </span>
                    <span class="w-full mt-auto text-sm text-gray-700">Fresh for <%= distance_of_time_in_words(Time.zone.now, stock.use_by_date) + (stock.use_by_date <= Time.zone.now ? ' ago': '')%></span>
                  <% end %>
                </div>
              <% end %>
            <% end %>
            <div class="order-3 non_sortable max-w-lg flex p-1 w-1/2 sm:w-1/3
                <% if user_cupboards(current_user).length > 1%>
                  md:w-1/2 lg:w-1/3 xl:w-1/4
                <% else %>
                  md:w-1/4 lg:w-1/5 xl:w-1/6
                <% end %>" style="min-height: 8rem;">
              <div class=" flex flex-col w-full bg-white rounded p-2 border border-solid border-primary-400">
                <%= link_to "Add typical ingredients", stocks_new_path(:cupboard_id => cupboard_id_hashids.encode(cupboard.id)), class: "m-1 rounded p-3 relative border border-solid border-primary-400 bg-primary-400 hover:bg-primary-300 focus:bg-primary-300 non_sortable" %>
                <%= link_to "Add other ingredient", stocks_custom_new_path(:cupboard_id => cupboard_id_hashids.encode(cupboard.id)), class: "m-1 rounded p-3 relative border border-solid border-primary-400 hover:bg-primary-100 focus:bg-primary-100 non_sortable" %>
              </div>
            </div>
          </div>
          <div class="w-full mt-auto flex justify-center">
            <% if cupboard.users.select{|u| u != current_user}.length < 1 %>
              <%= link_to "Add people to this cupboard", cupboard_share_path(cupboard_sharing_hashids.encode(cupboard.id)),
                  class: "w-full text-center px-4 py-5 bg-primary-200 border-t border-solid border-primary-400 text-base" %>
            <% else %>
              <%= link_to cupboard_share_path(cupboard_sharing_hashids.encode(cupboard.id)),
                  class: "w-full border-t border-solid border-primary-400 flex",
                  title: "Sharing settings" do %>
                <div class="w-full p-3 flex items-center hover:bg-primary-50">
                  <p class="text-base mr-3">
                    <span>Cupboard shared with: </span>
                    <span>
                      <%= cupboard.cupboard_users.select{|cu|cu.user != current_user}.map{|cu|cu.user.name}.to_sentence %>
                    </span>
                  </p>
                </div>
                <span class="text-4xl p-2 w-20 bg-primary-300 text-center hover:bg-primary-400">+</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="w-full px-4">
    <div class="w-full md:w-1/2 px-2">
      <%= link_to cupboards_new_path,
          class: "w-full bg-primary-100 block p-4 h-48 flex items-center justify-center rounded" do %>
      <span>Add a new cupboard</span>
      <% end %>
    </div>
  </div>
</div>

<div id="demo" hidden>
	<%= render "cupboards/partials/modal_content" %>
</div>

app/views/cupboards/partials/_modal_content.html.erb
<video autoplay poster="<%= asset_pack_path('assets/images/add_ingredients_flow_poster.png') %>" playsinline controls muted>
	<source src="<%= asset_pack_path('assets/videos/add_ingredients_flow_full.mp4') %>">
	<source src="<%= asset_pack_path('assets/videos/add_ingredients_flow_full.webm') %>">
</video>

app/views/cupboards/partials/_no_js_modal.html.erb
<div class="no-js-modal">
	<a href=<%= cupboards_path %> id="js-modal-overlay" class="modal-overlay" data-background-click="enabled" title="Close modal">
		<span class="invisible">Close modal</span>
	</a>
	<dialog id="js-modal" class="modal" role="dialog" open="" aria-labelledby="modal-title">
		<div role="document" class="modal__wrapper">
			<a href=<%= cupboards_path %> class="modal-close" title="Close modal">
				<img src=<%= png_icon_path('close') %> alt="Close modal" class="modal__closeimg">
			</a>
			<div class="modal__content">
				<h1 id="modal-title" class="modal-title">
				Quick demo on how to add ingredients
				</h1>
				<div id="demo" class="hidden">
					<%= render "cupboards/partials/modal_content" %>
			</div>
		</div>
	</dialog>
</div>